configuration: 
  name: oaqa-tutorial
  author: oaqa
collection-reader:
  inherit: collection_reader.filesystem-collection-reader
  InputDirectory: ../DataHTML
  
pipeline:
  - inherit: ecd.phase  
    name: HtmlCleaner
    options: |
      - inherit: cleaner.cleaner3

  - inherit: cas_consumer.text-file-writer3
