configuration: 
  name: oaqa-tutorial
  author: oaqa
collection-reader:
  inherit: collection_reader.filesystem-collection-reader
  InputDirectory: ../ProjectDataHTML
  #InputDirectory: ../ProjectSmallDataHTML
  #HtmlCleanerClass: cleaner.TikaHtmlCleaner
  HtmlCleanerClass: cleaner.ExternalHtmlCleaner
  extScript: ../scripts/html2text_delbrack.sh
  
pipeline:
  - inherit: ecd.phase  
    name: SentSplit
    options: |
      - inherit: sentsplit.sentsplit

  - inherit: ecd.phase
    name: SENNA
    option-timeout: 600
    options: |
      - inherit: parsers.senna

  - inherit: ecd.phase
    name: extract
    options: |
      - inherit: extractors.senna_extractor_helper

  #- inherit: cas_consumer.simple-print
  - inherit: cas_consumer.XmiWriterCasConsumer
  - inherit: cas_consumer.AnnotationPrinter
